# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('subject', models.CharField(max_length=30, verbose_name='标题')),
                ('email', models.EmailField(max_length=255, verbose_name='邮箱')),
                ('message', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
